-- SCRUM-118: Create table for agent-generated draft heat mitigation plans
-- Stores supervisor-requested AI draft plans from Bedrock agent

CREATE TABLE agent_draft_plans (
    id UUID PRIMARY KEY,
    site_id UUID NOT NULL,
    supervisor_id UUID NOT NULL,
    plan_context TEXT NOT NULL,
    recommended_actions TEXT,
    policy_rules_applied TEXT,
    forecast_data_used jsonb NOT NULL DEFAULT '{}'::jsonb,
    safety_considerations TEXT,
    estimated_duration_minutes INTEGER,
    model_id VARCHAR(255),
    model_version VARCHAR(50),
    approval_status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    approved_at TIMESTAMP WITH TIME ZONE,
    FOREIGN KEY (site_id) REFERENCES site(id) ON DELETE RESTRICT,
    FOREIGN KEY (supervisor_id) REFERENCES app_user(id) ON DELETE RESTRICT
);

-- Indexes for common queries
CREATE INDEX idx_agent_draft_plans_site_id ON agent_draft_plans(site_id);
CREATE INDEX idx_agent_draft_plans_supervisor_id ON agent_draft_plans(supervisor_id);
CREATE INDEX idx_agent_draft_plans_approval_status ON agent_draft_plans(approval_status);
CREATE INDEX idx_agent_draft_plans_site_supervisor_status
    ON agent_draft_plans(site_id, supervisor_id, approval_status);
CREATE INDEX idx_agent_draft_plans_created_at ON agent_draft_plans(created_at DESC);

-- Column comments for documentation
COMMENT ON TABLE agent_draft_plans IS 'AI-generated draft heat mitigation plans from Bedrock agent (SCRUM-118)';
COMMENT ON COLUMN agent_draft_plans.id IS 'Unique identifier for the draft plan';
COMMENT ON COLUMN agent_draft_plans.site_id IS 'Reference to the site this plan is for';
COMMENT ON COLUMN agent_draft_plans.supervisor_id IS 'Reference to the supervisor who requested the plan';
COMMENT ON COLUMN agent_draft_plans.plan_context IS 'Operational context provided to Bedrock agent for plan generation';
COMMENT ON COLUMN agent_draft_plans.recommended_actions IS 'AI-generated list of recommended actions for heat mitigation';
COMMENT ON COLUMN agent_draft_plans.safety_considerations IS 'AI-identified safety considerations and constraints';
COMMENT ON COLUMN agent_draft_plans.estimated_duration_minutes IS 'Estimated time to execute the plan';
COMMENT ON COLUMN agent_draft_plans.approval_status IS 'Status: PENDING (awaiting review), APPROVED, REJECTED, EXECUTED';
COMMENT ON COLUMN agent_draft_plans.created_at IS 'Timestamp when plan was generated by agent';
COMMENT ON COLUMN agent_draft_plans.updated_at IS 'Timestamp of last update';
COMMENT ON COLUMN agent_draft_plans.approved_at IS 'Timestamp when supervisor approved the plan';
