#!/usr/bin/env bash
set -euo pipefail
source "$(dirname "$0")/helpers/test-helpers.sh"

runbook="docs/runbooks/SCRUM-274-security-hub-inspector.md"
assert_file "$runbook"

assert_contains "$runbook" "Never run Terraform"
assert_contains "$runbook" "Terraform Validation"
assert_contains "$runbook" "Terraform State Plan"
assert_contains "$runbook" "Terraform State Apply"
assert_contains "$runbook" "plan run ID"
assert_contains "$runbook" "apply run ID"
assert_contains "$runbook" "resource delta"
assert_contains "$runbook" "Insight ARN"
assert_contains "$runbook" "manual"
assert_contains "$runbook" "human"
assert_contains "$runbook" "PENDING"
assert_contains "$runbook" "UNKNOWN"
assert_contains "$runbook" "FAILED"
assert_contains "$runbook" "NOT-VALIDATED"
assert_contains "$runbook" "LOADING"
assert_contains "$runbook" "EMPTY"
assert_contains "$runbook" "SUCCESS"
assert_contains "$runbook" "VALIDATION"
assert_contains "$runbook" "OFFLINE"
assert_contains "$runbook" "STALE"
assert_contains "$runbook" "DENIED"
assert_contains "$runbook" "ERROR"
assert_contains "$runbook" "must not be reported as clean"
assert_contains "$runbook" "Critical"
assert_contains "$runbook" "High"
assert_contains "$runbook" "ACTIVE"
assert_contains "$runbook" "NEW"
assert_contains "$runbook" "NOTIFIED"
assert_contains "$runbook" "repository"
assert_contains "$runbook" "image digest"
assert_contains "$runbook" "Jira"
assert_contains "$runbook" "replacement"
assert_contains "$runbook" "retry"
assert_contains "$runbook" "closure"
assert_contains "$runbook" "60 minutes"
assert_contains "$runbook" "one business day"
assert_contains "$runbook" "colour alone"
assert_contains "$runbook" "redact"
assert_contains "$runbook" "raw finding payload"
assert_contains "$runbook" "automated Jira creation"
assert_contains "$runbook" "automatic remediation"

# The runbook may describe forbidden scope, but it must never contain secrets,
# credentials, raw ASFF import calls, or executable mutation commands.
assert_not_contains "$runbook" "AWS_SECRET_ACCESS_KEY"
assert_not_contains "$runbook" "AWS_SESSION_TOKEN"
assert_not_contains "$runbook" "Authorization:"
assert_not_contains "$runbook" "BatchImportFindings"
assert_not_contains "$runbook" "securityhub:BatchImportFindings"
assert_not_contains "$runbook" "aws_securityhub_finding"
